# Generated by Django 6.0.1 on 2026-02-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('H', 'Alta'), ('M', 'Mitjana'), ('L', 'Baixa')], default='M', max_length=1)),
                ('detected_at', models.DateTimeField()),
            ],
        ),
    ]
